In [1]:
import numpy as np

까먹으면 안되는 두가지!
1. lookfor
2. info

In [3]:
np.lookfor('shape') ##괄호 뒤에 있는 메서드를 싹 다 보여준다~

Search results for 'shape'
--------------------------
numpy.shape
    Return the shape of an array.
numpy.reshape
    Gives a new shape to an array without changing its data.
numpy.flip
    Reverse the order of elements in an array along the given axis.
numpy.full
    Return a new array of given shape and type, filled with `fill_value`.
numpy.isin
    Calculates `element in test_elements`, broadcasting over `element` only.
numpy.ones
    Return a new array of given shape and type, filled with ones.
numpy.empty
    Return a new array of given shape and type, without initializing entries.
numpy.zeros
    Return a new array of given shape and type, filled with zeros.
numpy.resize
    Return a new array with the specified shape.
numpy.ndarray
    ndarray(shape, dtype=float, buffer=None, offset=0,
numpy.ndindex
    An N-dimensional iterator object to index arrays.
numpy.squeeze
    Remove single-dimensional entries from the shape of an array.
numpy.ma.shape
    Return the shape of an array.

In [4]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or a ctypes POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArr

In [6]:
a = np.array(100)
a ##0차!! 스칼라기때문에~

array(100)

In [7]:
a = np.array([1,2,3])#1차

In [10]:
a = np.array([[1,2,3],[4,5,6]])#1차
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.sum(a, axis=0) ## 0이 axis에서 row 1이 column
##여러 값을 하나로 줄여주는 것 -> Reduction
##Numpy에는 Stride개념이 숨어져있다!!

array([5, 7, 9])

## 모양 바꾸기~

In [14]:
a = np.arange(27)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [16]:
a.shape ##튜플이기때문에 27!

(27,)

In [18]:
a.reshape(3,9) ##모양 맞출때 조심해야함!!
##뮤터블이고, 자기 자신이 바뀌지 않는다!
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [19]:
b = a.reshape(3,9)

In [20]:
b[0][0] = 100

In [21]:
a ## 골때리쥬?? reshape 한걸 바꿔도 a가 바꿔버린다~
## 그래서 Copy를 한다!! 이동네 카피는 기본적으로 Deep Copy이다~

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26])

In [24]:
b = a.reshape(3,-1).copy()
b = a.reshape(-1,9).copy()
##-만 들어가도 되긴한다. 그런데 관례상 -1을 사용한다!

In [25]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [28]:
b = a.reshape(3,-2).copy()
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [42]:
a = np.arange(27)
a.resize((3,9))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

reshape의 경우 원본이 바꾸지 않아서, 재할당을 통해 다시 줘야함.

resize의 경우 뮤터블 자기 자신이 바뀜!

그래서 상황에 따라서 사용할 것!

In [32]:
a = np.arange(27)
a.resize((3,5))
a
## 계산을 똑바로 안하면 지가 그냥 잘라버림~

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
a = np.arange(27)
a.resize((3,10))
a
#더 크게 하면 지가 알아서 0으로 채워 넣음

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26,  0,  0,  0]])

In [34]:
a = np.arange(27)
a.resize((-1,10))
a
##resize는 -처리를 안함...
## 그리고 대부분의 책에 reshape으로 함! 그리고 뮤터블은 재할당

ValueError: negative dimensions not allowed

In [43]:
a = np.arange(27)
a.resize((3,9))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [36]:
'split' in dir(a)
##Function방식에 없으면 메서드 방식!

False

In [44]:
np.split(a,(1,2))
## 튜플형태로 자른다
## 0 에서 1까지, 1에서 2까지, 2에서 끝까지

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [45]:
np.split(a,(2,2))
##0에서 2까지 그리고 빈것 2에서 끝까지

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([], shape=(0, 9), dtype=int32),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [46]:
np.split(a,(2,5))
## 1개 입력하면 2개가 되고, 2개 입력하면 3개로 쪼개짐
## 없으면 빈것ㄷ으로!

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int32)]

In [47]:
np.split(a,(-2,5)) ##0이 기준인데...

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int32)]

In [48]:
np.split(a,(5,5),axis=1)
## 항상 빈 것이 생긴다~~
## 너무 불편해! 그래서 hsplit

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]),
 array([], shape=(3, 0), dtype=int32),
 array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

In [51]:
np.hsplit(a,(5,))
## 어떤개념?? 튜플개념!!
## 구분선을 없애고 자를 수 있다.

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]), array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

In [52]:
np.vsplit(a,(2,))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

사실 split하나만 알고 있다면 모든게 해결된다~

axis0 -> hsplit, axis1 -> vsplit4

split이 있다면! 합치는게 있을 것! ... Stack

In [53]:
b = np.arange(5)
c = np.arange(5,10)

In [54]:
np.stack((b,c))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
np.stack((b,c),axis=1)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [57]:
np.hstack((b,c))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np.vstack((b,c))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
np.r_[b,c] ##hstack과 같음! r:row

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.c_[b,c] ##vstack과 같음 c:column

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [65]:
np.arange(10)[np.s_[1]] ##slice 개체를 만들어 주는 아이가 s_

1

In [66]:
[1,2,3,4,5,][slice(1,5)]

[2, 3, 4, 5]

In [67]:
np.column_stack([b,c]) ##stack(, axis=1), np.c_ 이것들과 같다.

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [72]:
a = np.arange(6)

In [71]:
a = np.array([[0,1,2,3,4,5]])
a ##결국 a를 이렇게 바꾸고 싶다!

array([[0, 1, 2, 3, 4, 5]])

In [69]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [73]:
a[np.newaxis] ##괄호하나 더 넣고 싶은 것...

array([[0, 1, 2, 3, 4, 5]])

In [74]:
np.newaxis is None

True

In [76]:
a = a.reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [77]:
a[np.newaxis] ##3차원으로 바뀌어버린다.

array([[[0, 1, 2],
        [3, 4, 5]]])

In [78]:
a[:,np.newaxis]

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [79]:
a[:,:,np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [80]:
a = np.arange(6)

In [81]:
a[:,np.newaxis]
##넘파이는 shape을 맞춰야하는데, shape을 자유자제로 바꾸기 위해~ 존재

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [82]:
np.expand_dims(a,1) ##이 아이는 저어어어어어어어ㅓㅇ어ㅓㅇ말 많이 쓸 것이다!
#모양바꾸는데 매우 파워풀

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [83]:
np.expand_dims(a,2)
##파워풀 하다만, 차원을 한개씩밖에 바꿔주지 못한다...

C:\Users\Ikjong\Anaconda3\envs\cuda\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Both axis > a.ndim and axis < -a.ndim - 1 are deprecated and will raise an AxisError in the future.
  """Entry point for launching an IPython kernel.


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [87]:
a = np.arange(27).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [88]:
np.moveaxis(a,0,2)

array([[[ 0,  9, 18],
        [ 1, 10, 19],
        [ 2, 11, 20]],

       [[ 3, 12, 21],
        [ 4, 13, 22],
        [ 5, 14, 23]],

       [[ 6, 15, 24],
        [ 7, 16, 25],
        [ 8, 17, 26]]])

## Structured arrays

이거 기반으로 판다스를 만듬!

넘파이는 기본으로 Homogeneous! but 사용자 지정을 통해서 다르게 가능!!

나만의 데이터 구조를 만들 수 있다.

but!! 이름에 무조건 문자열이 들어가야한다!!

키방식 - 열추출

인덱싱 or 슬라이싱 - 행추출

파이썬에서 namedtuple과 바슷함...

In [107]:
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
x

TypeError: data type not understood

In [91]:
x[0], x[1]

(('Rex', 9,  81.), ('Fido', 3,  27.))

In [92]:
x['age']

array([9, 3])

In [93]:
x['age'] = 5
x

array([('Rex', 5,  81.), ('Fido', 5,  27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [103]:
x['name'] ##key 방식 접근!

array(['Rex', 'Fido'],
      dtype='<U10')

In [106]:
'name' in dir(x)
##이 아이는 attribute 방식으로는 접근하지 못한다...
##namedtuple의 경우 key방식으로 접근 X

False

structured array는 행으로도, 열로도 모두 접근이 가능하다!!

넘파이로 이런 개체들을 관리하면 효율적으로 관리가 가능하다!!

메모리에 올리기 때문에 빠르기도 하다!

메모리에 못올리는 경우?? Dask

In [94]:
from collections import namedtuple

In [95]:
Address = namedtuple('Address', ('name','age','weight'))

In [96]:
a1 = Address('Rex', 27,81.0) ##마치 클래스방식!!

In [97]:
a1.name

'Rex'

In [102]:
a1['name']
## tuple이기때문에 이렇게 접근은 안됨!

TypeError: tuple indices must be integers or slices, not str

In [101]:
a1[0], a1[1], a1[2]

('Rex', 27, 81.0)

In [99]:
dir(a1)
##count, index는 tuple에 있었던 것!
## namedtuple을 사용하면, DB처럼 사용하고 싶은걸 해결! 
## cf)메타클래스... 클래스 생성하지 않고 클래스로! 

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '_asdict',
 '_fields',
 '_make',
 '_replace',
 '_source',
 'age',
 'count',
 'index',
 'name',
 'weight']

팁!! 파이썬에는 날짜를 관리하는 패키지가 3개가 있다
1. time
2. calendar
3. datetime ... 

In [1]:
import datetime

In [2]:
dir(datetime)

['MAXYEAR',
 'MINYEAR',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_divide_and_round',
 'date',
 'datetime',
 'datetime_CAPI',
 'time',
 'timedelta',
 'timezone',
 'tzinfo']

In [20]:
##관례상 이런식으로 사용한다.
from datetime import datetime, timedelta, date, time

In [8]:
aa = datetime.today()

In [9]:
aa

datetime.datetime(2019, 7, 23, 15, 38, 35, 348454)

In [10]:
a = datetime(2019,7,22)

In [11]:
dir(a)

['__add__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rsub__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 'astimezone',
 'combine',
 'ctime',
 'date',
 'day',
 'dst',
 'fromordinal',
 'fromtimestamp',
 'hour',
 'isocalendar',
 'isoformat',
 'isoweekday',
 'max',
 'microsecond',
 'min',
 'minute',
 'month',
 'now',
 'replace',
 'resolution',
 'second',
 'strftime',
 'strptime',
 'time',
 'timestamp',
 'timetuple',
 'timetz',
 'today',
 'toordinal',
 'tzinfo',
 'tzname',
 'utcfromtimestamp',
 'utcnow',
 'utcoffset',
 'utctimetuple',
 'weekday',
 'year']

In [13]:
a.year, a.month, a.day

(2019, 7, 22)

In [18]:
b = timedelta(3)

In [21]:
a = datetime.strptime('2019-07-23', '%Y-%m-%d') ##시간날짜 고유 포맷이 있다.

In [22]:
a

datetime.datetime(2019, 7, 23, 0, 0)

In [24]:
import numpy as np

In [25]:
np.lookfor('casting')

Search results for 'casting'
----------------------------
numpy.abs
    Calculate the absolute value element-wise.
numpy.add
    Add arguments element-wise.
numpy.cos
    Cosine element-wise.
numpy.exp
    Calculate the exponential of all elements in the input array.
numpy.log
    Natural logarithm, element-wise.
numpy.mod
    Return element-wise remainder of division.
numpy.sin
    Trigonometric sine, element-wise.
numpy.tan
    Compute tangent element-wise.
numpy.cbrt
    Return the cube-root of an array, element-wise.
numpy.ceil
    Return the ceiling of the input, element-wise.
numpy.conj
    Return the complex conjugate, element-wise.
numpy.cosh
    Hyperbolic cosine, element-wise.
numpy.exp2
    Calculate `2**p` for all `p` in the input array.
numpy.fabs
    Compute the absolute values element-wise.
numpy.fmax
    Element-wise maximum of array elements.
numpy.fmin
    Element-wise minimum of array elements.
numpy.fmod
    Return the element-wise remainder of division.
numpy.isin


In [26]:
a = np.array([1,2,3])

In [27]:
a

array([1, 2, 3])

In [30]:
a.dtype = 'int8'

In [31]:
a

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0], dtype=int8)

In [33]:
a.astype('float32')

array([ 1.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  3.,  0.,  0.,  0.], dtype=float32)