## 기계학습

**Data**로부터

**Specific** 문제 **해결**을 위한

**최적의** 모델 만들기

(성능도 좋아야 함! + Unseen(보지못한))

CS관점 **무조건** 결과가 좋으면 된다~

bias - 결과와 떨어진 정도

variance - 퍼져있는 정도

### 이 과정에서는 Model Selection을 할 것이다!

In [20]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
##load_는 크기가 작은 데이터
##fetch는 인터넷에서 가져와서 큰 데이터
##make는 생성해서 만드는 데이터
##load_irs -> function이다!! snake방식

In [12]:
data = load_iris()

In [13]:
data
##numpy 기반 ...gpu 지원 x

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [14]:
type(data)
##Bunch는 쪼갤 수 있다~

sklearn.utils.Bunch

In [17]:
dir(data)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [19]:
print(data.DESCR)
##기본적으로 classification
##싸이킷에서는 타겟이름 피쳐 네임 등이 있다~
##그리고 우리는 이것을 판다스로 할 것이다~

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [38]:
iris = pd.DataFrame(data.data,columns=names)

In [30]:
names = data.feature_names
names[0][:-5].replace(" ","_")

'sepal_length'

In [37]:
names =[x[:-5].replace(" ","_") for x in names]

In [39]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [40]:
data.target_names

array(['setosa', 'versicolor', 'virginica'],
      dtype='<U10')

In [41]:
iris_target = pd.DataFrame(data.target, columns=['target'])

In [43]:
iris_target.head()

target
0       0
1       0
2       0
3       0
4       0

In [44]:
iris = pd.concat([iris,iris_target],axis=1)

In [46]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

세상에 잘 정제되고 좋은 데이터가 얼마없다.... 그래서 좋은 알고리즘이 필요하다!

기존의 있던 논문들은 좋은 알고리즘이 중요하다! 라고들 함

1. 모델을 사용하고 싶으면 알고리즘 불러오기
2. 인스턴스화
3. Train(CS) / Fit(Stat)

In [47]:
from sklearn.neighbors import KNeighborsClassifier

In [60]:
knn = KNeighborsClassifier()

In [54]:
iris.columns[:-1]

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')

In [57]:
iris.iloc[:,:-1].head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [58]:
knn.fit(iris.iloc[:,:-1],iris[iris.columns[-1]])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [73]:
knn2 = KNeighborsClassifier(3)

In [74]:
knn2.fit(iris.iloc[:,:-1],iris[iris.columns[-1]])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [75]:
vars(knn2)

{'_fit_X': array([[ 5.1,  3.5,  1.4,  0.2],
        [ 4.9,  3. ,  1.4,  0.2],
        [ 4.7,  3.2,  1.3,  0.2],
        [ 4.6,  3.1,  1.5,  0.2],
        [ 5. ,  3.6,  1.4,  0.2],
        [ 5.4,  3.9,  1.7,  0.4],
        [ 4.6,  3.4,  1.4,  0.3],
        [ 5. ,  3.4,  1.5,  0.2],
        [ 4.4,  2.9,  1.4,  0.2],
        [ 4.9,  3.1,  1.5,  0.1],
        [ 5.4,  3.7,  1.5,  0.2],
        [ 4.8,  3.4,  1.6,  0.2],
        [ 4.8,  3. ,  1.4,  0.1],
        [ 4.3,  3. ,  1.1,  0.1],
        [ 5.8,  4. ,  1.2,  0.2],
        [ 5.7,  4.4,  1.5,  0.4],
        [ 5.4,  3.9,  1.3,  0.4],
        [ 5.1,  3.5,  1.4,  0.3],
        [ 5.7,  3.8,  1.7,  0.3],
        [ 5.1,  3.8,  1.5,  0.3],
        [ 5.4,  3.4,  1.7,  0.2],
        [ 5.1,  3.7,  1.5,  0.4],
        [ 4.6,  3.6,  1. ,  0.2],
        [ 5.1,  3.3,  1.7,  0.5],
        [ 4.8,  3.4,  1.9,  0.2],
        [ 5. ,  3. ,  1.6,  0.2],
        [ 5. ,  3.4,  1.6,  0.4],
        [ 5.2,  3.5,  1.5,  0.2],
        [ 5.2,  3.4,  1.4,  0.2],
    

In [76]:
knn2.predict(np.array([[3,3,3,3]]))

array([1])

In [77]:
data.target_names

array(['setosa', 'versicolor', 'virginica'],
      dtype='<U10')

In [78]:
knn2.predict(np.array([[3,4,1,2],[3,3,3,3]]))

array([0, 1])

In [79]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [80]:
a = np.array([1,2,3,4]).reshape(1,4)
a

array([[1, 2, 3, 4]])

In [81]:
knn2.predict_proba(np.array([[3,4,1,2],[3,3,3,3]]))

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.66666667,  0.33333333]])

하이퍼 파라메타 튜닝은
1. grid-search
2. randomize-search

를 한 후 모델 셀렉션을 하면 된다~

In [83]:
knn2.get_params() ##내가 바꿀 수 있는 하이퍼파라메타들!
##n_jobs는 무엇일까?? n은 보통 number!
##몇 개의 core를 가지고 학습을 시킬 것이냐?
##모델은 정확성도 중요하지만 속도도 중요하다!!
##딥러닝은 모델 학습은 엄청 시간이 걸리지만, 예측은 얼마 안걸린다~

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 3,
 'p': 2,
 'weights': 'uniform'}

In [84]:
knn2 = KNeighborsClassifier(3,n_jobs=-1)
##내가 쓸 수 있는 코어를 다 쓰는 것!